/*
This has been generated by the overpass-turbo wizard.
The original search was:
“railway=rail”
*/
[out:json][timeout:25];

( area[name="България"]; )->.a; 

// gather results
(
  // query part for: “railway=rail”
  node["railway"="station"]["station"!~"subway"](area.a);
  way["railway"="rail"](area.a);
);
// print results
out body;
>;
out skel qt;

{{style:
node[railway=station]{ 
  text : name;
  color: red;
  fill-color:yellow;
  fill-opacity:1.0;
}
}}